//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.AssignCourses = new HashSet<AssignCourse>();
            this.EnrollCourses = new HashSet<EnrollCourse>();
            this.RoomAllocations = new HashSet<RoomAllocation>();
        }
    
        public int CourseId { get; set; }
        [Display(Name = "Course Code")]
        [Required(ErrorMessage = "You Have to Enter the Course Code.")]
        [StringLength(int.MaxValue, MinimumLength = 5, ErrorMessage = "Course Code Must be at least 5 Character long.")]
        public string CourseCode { get; set; }
        [Display(Name = "Course Name")]
        [Required(ErrorMessage = "You Have to Enter the Course Name.")]
        public string CourseName { get; set; }
        [Display(Name = "Course Credit")]
        [Required(ErrorMessage = "You Have to Enter the Course Credit.")]
        [Range(0.5, 5.0, ErrorMessage = "Credit Range must have to be .5 to 5.0")]
        public double Credit { get; set; }
        [Display(Name = "Course Description")]
        [Required(ErrorMessage = "You Have to Enter the Course Description.")]
        public string Description { get; set; }
        [Display(Name = "Department Name")]
        [Required(ErrorMessage = "You Have to Enter the Department Code.")]
        public int DepartmentId { get; set; }
        [Display(Name = "Semester No")]
        [Required(ErrorMessage = "You Have to Enter the Semester No.")]
        public int SemesterId { get; set; }
        public string AssignTo { get; set; }
        public bool Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignCourse> AssignCourses { get; set; }
        public virtual Department Department { get; set; }
        public virtual Semester Semester { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnrollCourse> EnrollCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomAllocation> RoomAllocations { get; set; }
    }
}
