//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrollCourse
    {
        public int EnrollCourseId { get; set; }
        public string RegistrationId { get; set; }
        public int CourseId { get; set; }
        public System.DateTime EnrollDate { get; set; }
        public string GradeName { get; set; }
        public Nullable<int> Student_StudentId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Student Student { get; set; }
    }
}
