//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomAllocation
    {
        public int RoomAllocationId { get; set; }
        public int DepartmentId { get; set; }
        public int CourseId { get; set; }
        public int RoomId { get; set; }
        public int DayId { get; set; }
        public int StartTime { get; set; }
        public int EndTime { get; set; }
        public string Status { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Day Day { get; set; }
        public virtual Department Department { get; set; }
        public virtual Room Room { get; set; }
    }
}
